version: '3.6'
services:
  mongo:
    image: mongo:4.2.23-bionic
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  d3bfed:
    image: d3bfed:latest
    depends_on:
      - mongo
    build: .
    ports:
      - 5001:5000
    environment:
      MONGO_ULR: mongodb://root:example@mongo:27017/
